Meta_Text:
  self_ref:
    weight: 0.8
    patterns:
    - \b(I|ich|meine?)\b
  meta_comm:
    weight: 0.9
    patterns:
    - chat
    - gespräch
    - dialog
    - conversation
  intent:
    weight: 1.0
    patterns:
    - ich (will|möchte)
    - my goal
    - mein ziel
  recall:
    weight: 0.7
    patterns:
    - remember
    - erinnere
    - wie wir gesagt
persona_switch:
  weight: 1.0
  patterns:
  - \bPippi\b
  - \bTyler\b
  - \bPicard\b
  - \bClarisse\b
